# Generated by Django 3.1.7 on 2021-05-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
