# Generated by Django 3.1.7 on 2021-05-14 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_order_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='date_of_order',
        ),
        migrations.AddField(
            model_name='address',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customermenuitem',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_date',
            field=models.DateTimeField(null=True),
        ),
    ]
