# Generated by Django 3.1.7 on 2021-05-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210514_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='placeanorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.order'),
        ),
        migrations.AlterField(
            model_name='customermenuitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.order'),
        ),
        migrations.DeleteModel(
            name='PlaceAnOrder',
        ),
    ]
