# Generated by Django 3.1.7 on 2021-05-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
