# Generated by Django 3.1.7 on 2021-05-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210514_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
