# Generated by Django 3.1.7 on 2021-05-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210514_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='to',
            field=models.TimeField(null=True),
        ),
    ]
